version: "1"

services:
  user-service:
    path: /Users/vivekkundariya/Personal/grund/docs/demo/user-service

  order-service:
    path: /Users/vivekkundariya/Personal/grund/docs/demo/order-service

  notification-service:
    path: /Users/vivekkundariya/Personal/grund/docs/demo/notification-service
